---
name: Build & Deploy

env:
  ARTIFACT_NAME: csye-serverless-${{ github.run_number }}.zip
  LAMBDA_FUNCTION_NAME: serverless
  AWS_REGION: us-east-1

on: [push]
  # push:
  #  branches: [ master ]

jobs:
  ci_cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout
        run: pwd; ls -l

      - name: Build deployment artifact
        run: |
          mkdir codedeploy_artifact
          zip -r ${{ env.ARTIFACT_NAME }} lambda_function.py
          mv ${{ env.ARTIFACT_NAME }} codedeploy_artifact

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Copy artifact to S3
        run: |
          aws s3 sync ./codedeploy_artifact s3://${{ secrets.S3_CODEDEPLOY_BUCKET }}

      - name: Update lambda function
        run: |
          aws lambda update-function-code \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --s3-bucket s3://${{ secrets.S3_CODEDEPLOY_BUCKET }} \
          --s3-key ${{ env.ARTIFACT_NAME }}


